### ISSUE TITLE
Device not working after uploading the latest code

### ISSUE THREAD

**Issue by jonjander** [bobricius/armachat#2]
Arduino IDE log:
Sketch uses 43176 bytes (17%) of program storage space. Maximum is 253952 bytes.
Atmel SMART device 0x1001000a found
Device       : ATSAMD21E18A
Chip ID      : 1001000a
Version      : v1.1 [Arduino:XYZ] Jul 14 2020 23:30:13
Address      : 8192
Pages        : 3968
Page Size    : 64 bytes
Total Size   : 248KB
Planes       : 1
Lock Regions : 16
Locked       : none
Security     : false
Boot Flash   : true
BOD          : true
BOR          : true
Arduino      : FAST_CHIP_ERASE
Arduino      : FAST_MULTI_PAGE_WRITE
Arduino      : CAN_CHECKSUM_MEMORY_BUFFER
Erase flash
done in 0.871 seconds

Write 43840 bytes to flash (685 pages)
[==============================] 100% (685/685 pages)
done in 0.283 seconds

Verify 43840 bytes of flash with checksum.
Verify successful
done in 0.072 seconds
CPU reset.

Device resets and then it's all black. Nothing is happening.

**Comment by jonjander** [comment]
I have followed this instructions. https://hackaday.io/project/171790/instructions 
The screen flashes 2-3 times when it boots.

**Comment by bobricius** [comment]
which board you have?

**Comment by bobricius** [comment]
Uploaded last code version
