### ISSUE TITLE
Both of my Armachat Compact Doomsday Communicators won’t boot.

### ISSUE THREAD

**Issue by jeremyseda** [bobricius/armachat#8]
Hi there,

I’m rather new to the world of iOT.  I purchased a couple of Doomsday Communicators and both of the devices recently stopped booting.  The red power light stays solid and the green ACT light goes solid and then flashes 7 times.  I guess that means that the kernel.img is not found (https://www.partitionwizard.com/partitionmagic/raspberry-pi-not-booting.html)?  What files would you recommend I install from your [GitHub post](https://github.com/bobricius/armachat)?  Many thanks!

**Comment by bobricius** [comment]
delete all files from device and copy fresh from here https://github.com/bobricius/Armachat-circuitpython/tree/main/Software

**Comment by jeremyseda** [comment]
Thank you for your reply.  I'm now getting one of the devices to display some sort of error message:
...
Starting code.py...
Traceback (most recent call last):
  File "code.py", line 9, in <module>
MpyError: Incompatible .mpy file. Please update all .mpy files.  See http://adafru.it/mpy-update for more info.

Code done running. 

Any other suggestions?  Many thanks for your help.

**Comment by jeremyseda** [comment]
For anyone else experiencing this same issue, here's what I did to fix my Armachat Doomsday Communicators:

- Went to http://adafru.it/mpy-update > I went to the **ValueError: Incompatible .mpy files** section and was directed to: https://github.com/adafruit/Adafruit_CircuitPython_Bundle/releases/latest
- Once I figured out that I was running Circuit Python v 7.x, I download the correct corresponding files from: https://github.com/adafruit/Adafruit_CircuitPython_Bundle/releases/download/20221219/adafruit-circuitpython-bundle-7.x-mpy-20221219.zip
- The startup error messages then pointed me to several .mpy files that were incompatible.  After finally replacing all incompatible files, I was able to get my Armachat Doomsday Communicators to boot up as expected.
